GET http://localhost:3000/posts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiS3Jpc3RlbiIsImlhdCI6MTYyNDAzNjE5N30.i3f9nHF8MH7XhZavXtY8K1nh4mFHXxf206RRSgrJWmk
###


POST http://localhost:3000/login
Content-Type: application/json

{
  "username": "Kristen",
  "password": "password"
}
